version: "3.8"

networks:
  loadbalancer:
    external: true

services:
  pln-marketplace-theoden-development:
    image: $DOCKER_IMAGE
    networks:
      - loadbalancer
    volumes:
      - /etc/localtime:/etc/localtime:ro
    logging:
      driver: loki
      options:
        loki-url: "$DATASOURCE_LOKI"
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.services.pln-marketplace-theoden-development.loadbalancer.server.port=80"
        - "traefik.http.middlewares.compress-pln-marketplace-theoden-development.compress=true"
        - "traefik.http.middlewares.redirectscheme-pln-marketplace-theoden-development.redirectscheme.scheme=https"
        - "traefik.http.routers.pln-marketplace-theoden-development-web.rule=Host(`dev-sellermkp.beyondkwh.id`)"
        - "traefik.http.routers.pln-marketplace-theoden-development-web.middlewares=compress-pln-marketplace-theoden-development"
        - "traefik.http.routers.pln-marketplace-theoden-development-web.entrypoints=web"
        - "traefik.http.routers.pln-marketplace-theoden-development-websecure.rule=Host(`dev-sellermkp.beyondkwh.id`)"
        - "traefik.http.routers.pln-marketplace-theoden-development-websecure.middlewares=redirect-pln-marketplace-theoden-development"
        - "traefik.http.routers.pln-marketplace-theoden-development-websecure.tls=true"
        - "traefik.http.routers.pln-marketplace-theoden-development-websecure.entrypoints=websecure"
      mode: replicated
      replicas: 1
      placement:
        max_replicas_per_node: 1
        constraints:
          - node.labels.ip == 10.14.204.124
        preferences:
          - spread: node.labels.ip
      resources:
        limits:
          memory: $DOCKER_MEM_LIMIT
