version: "3.8"

networks:
  loadbalancer:
    external: true

services:
  pln-marketplace-theoden-staging:
    image: $DOCKER_IMAGE
    networks:
      - loadbalancer
    volumes:
      - /etc/localtime:/etc/localtime:ro
    logging:
      driver: loki
      options:
        loki-url: "$DATASOURCE_LOKI"
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.services.pln-marketplace-theoden-staging.loadbalancer.server.port=80"
        - "traefik.http.middlewares.compress-pln-marketplace-theoden-staging.compress=true"
        - "traefik.http.middlewares.redirectscheme-pln-marketplace-theoden-staging.redirectscheme.scheme=https"
        - "traefik.http.routers.pln-marketplace-theoden-staging-web.rule=Host(`sta-sellermkp.beyondkwh.id`)"
        - "traefik.http.routers.pln-marketplace-theoden-staging-web.middlewares=compress-pln-marketplace-theoden-staging"
        - "traefik.http.routers.pln-marketplace-theoden-staging-web.entrypoints=web"
        - "traefik.http.routers.pln-marketplace-theoden-staging-websecure.rule=Host(`sta-sellermkp.beyondkwh.id`)"
        - "traefik.http.routers.pln-marketplace-theoden-staging-websecure.middlewares=redirect-pln-marketplace-theoden-staging"
        - "traefik.http.routers.pln-marketplace-theoden-staging-websecure.tls=true"
        - "traefik.http.routers.pln-marketplace-theoden-staging-websecure.entrypoints=websecure"
      mode: replicated
      replicas: 1
      placement:
        max_replicas_per_node: 1
        constraints:
          - node.labels.ip == 10.14.204.125
        preferences:
          - spread: node.labels.ip
      resources:
        limits:
          memory: $DOCKER_MEM_LIMIT
